version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
